#!/usr/bin/env bash
# Split-tunnel mode: send only the domains listed in split-tunnel-domains.txt
# through ciadpi and let everything else connect directly.
#
# The service_install_* scripts set a system-wide SOCKS proxy, so every TLS
# connection goes through the desync. That also hits sites which were never
# blocked, and some of them reject the split ClientHello (sahibinden.com
# answers "sslv3 alert illegal parameter", vercel.com and others just time
# out). This script swaps the system-wide SOCKS setting for a PAC file that
# matches the domain list.
#
# Run it after a service_install_* script. Usage: sudo ./split_tunnel.sh on|off|status

set -euo pipefail

ETC_DIR="/usr/local/etc/goodbyedpi-turkey"
PAC_FILE="$ETC_DIR/proxy.pac"
PAC_PORT="1085"
PAC_URL="http://127.0.0.1:$PAC_PORT/proxy.pac"
PAC_LABEL="com.cagritaskn.goodbyedpi-turkey-pac"
PAC_PLIST="/Library/LaunchDaemons/$PAC_LABEL.plist"
SOCKS_HOST="127.0.0.1"
SOCKS_PORT="1080"
DOMAINS_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/split-tunnel-domains.txt"
DOMAINS="$ETC_DIR/split-tunnel-domains.txt"

[[ $EUID -eq 0 ]] || { echo "sudo ile calistirin: sudo $0 ${1:-}" >&2; exit 1; }

# Apply to every enabled service, not just the active one: a PAC set only on
# Wi-Fi stops applying as soon as the Mac switches to ethernet or tethering.
services() {
    networksetup -listallnetworkservices | tail -n +2 | grep -v '^\*' || true
}

write_pac() {
    mkdir -p "$ETC_DIR"
    [[ -f "$DOMAINS" ]] || cp "$DOMAINS_SRC" "$DOMAINS"
    {
        echo "// Generated by split_tunnel.sh from $DOMAINS"
        echo "function FindProxyForURL(url, host) {"
        echo "  if ("
        grep -vE '^[[:space:]]*(#|$)' "$DOMAINS" | while read -r d; do
            echo "      shExpMatch(host, \"$d\") || shExpMatch(host, \"*.$d\") ||"
        done
        echo "      false"
        echo "  ) {"
        echo "    return \"SOCKS5 $SOCKS_HOST:$SOCKS_PORT; SOCKS $SOCKS_HOST:$SOCKS_PORT\";"
        echo "  }"
        echo "  return \"DIRECT\";"
        echo "}"
    } >"$PAC_FILE"
    chmod 644 "$PAC_FILE"
}

# Chromium (Discord, Chrome) refuses file:// PAC URLs, so the file has to be
# served over HTTP. python3 ships with the Command Line Tools this port needs.
install_pac_server() {
    cat >"$PAC_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PAC_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/python3</string>
        <string>-m</string>
        <string>http.server</string>
        <string>$PAC_PORT</string>
        <string>--bind</string>
        <string>127.0.0.1</string>
        <string>--directory</string>
        <string>$ETC_DIR</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
PLIST
    chmod 644 "$PAC_PLIST"
    launchctl bootout "system/$PAC_LABEL" 2>/dev/null || true
    launchctl bootstrap system "$PAC_PLIST"
}

case "${1:-status}" in
on)
    write_pac
    install_pac_server
    for _ in {1..20}; do
        curl -sf --max-time 2 --noproxy '*' "$PAC_URL" >/dev/null 2>&1 && break
        sleep 0.25
    done
    curl -sf --max-time 3 --noproxy '*' "$PAC_URL" >/dev/null 2>&1 \
        || { echo "PAC sunucusu ($PAC_URL) baslatilamadi." >&2; exit 1; }
    while read -r svc; do
        networksetup -setsocksfirewallproxystate "$svc" off || true
        networksetup -setautoproxyurl "$svc" "$PAC_URL" || true
        networksetup -setautoproxystate "$svc" on || true
    done < <(services)
    echo "Split tunnel acik. ciadpi'den gecen domainler ($DOMAINS):"
    grep -vE '^[[:space:]]*(#|$)' "$DOMAINS" | sed 's/^/  - /'
    ;;
off)
    launchctl bootout "system/$PAC_LABEL" 2>/dev/null || true
    rm -f "$PAC_PLIST"
    while read -r svc; do
        networksetup -setautoproxystate "$svc" off || true
        networksetup -setsocksfirewallproxy "$svc" "$SOCKS_HOST" "$SOCKS_PORT" || true
        networksetup -setsocksfirewallproxystate "$svc" on || true
    done < <(services)
    echo "Split tunnel kapali; sistem geneli SOCKS geri acildi."
    ;;
status)
    while read -r svc; do
        printf '%-22s PAC=%s SOCKS=%s\n' "$svc" \
            "$(networksetup -getautoproxyurl "$svc" 2>/dev/null | tr '\n' ' ')" \
            "$(networksetup -getsocksfirewallproxy "$svc" 2>/dev/null | awk -F': ' '/^Enabled/{print $2}')"
    done < <(services)
    ;;
*)
    echo "kullanim: sudo $0 {on|off|status}" >&2
    exit 1
    ;;
esac
